/**
 * Test script for OpenAI-powered social media post generation
 * Run with: npx tsx scripts/testOpenAIPostGeneration.ts
 */

import { SocialMediaPostGenerator } from '../lib/socialMediaPostGenerator'
import { Citizen } from '../types/citizens'

// Sample citizen data for testing
const sampleCitizens: Citizen[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@techcorp.com',
    role: 'Software Engineer',
    initials: 'SJ',
    avatarColor: 'bg-blue-500',
    monetaryValue: 75000,
    age: 28,
    company: 'TechCorp',
    gender: 'female',
    personality: {
      traits: ['analytical', 'creative', 'collaborative'],
      workStyle: 'agile development; user-focused',
      socialStyle: 'collaborative; enjoys team work',
      motivation: 'innovation, problem-solving, growth',
      stressTriggers: ['tight deadlines', 'unclear requirements'],
      riskTolerance: 0.7,
      summary: 'experienced software engineer focused on innovation',
      category: 'engineer',
      ageBand: 'mid',
      interests: ['technology', 'coding', 'teamwork'],
      likes: ['clean code', 'user feedback', 'collaboration'],
      dislikes: ['technical debt', 'poor documentation'],
      values: ['quality', 'innovation', 'teamwork'],
      beliefs: ['code should be readable', 'users come first'],
      fears: ['technical stagnation', 'poor user experience'],
      aspirations: ['technical leadership', 'mentoring others'],
      habits: ['code reviews', 'continuous learning'],
      goals: ['improve code quality', 'mentor juniors'],
      challenges: ['balancing features and quality'],
      strengths: ['problem-solving', 'communication', 'adaptability'],
      weaknesses: ['perfectionism', 'over-engineering'],
      preferences: ['agile methodology', 'user-centered design'],
      behaviors: ['proactive', 'collaborative'],
      patterns: ['iterative development', 'continuous improvement'],
      triggers: ['unclear requirements', 'technical debt'],
      reactions: ['asks clarifying questions', 'proposes solutions'],
      responses: ['collaborative problem-solving', 'seeks feedback'],
      motivations: ['technical excellence', 'user satisfaction'],
      frustrations: ['poor requirements', 'technical debt']
    },
    socialMedia: {
      linkedIn: {
        url: 'https://linkedin.com/in/sarahjohnson',
        headline: 'Software Engineer at TechCorp',
        summary: 'Passionate about building great software',
        connections: 500,
        followers: 200,
        location: 'San Francisco, CA',
        currentRole: { title: 'Software Engineer', company: 'TechCorp', startYear: 2020 },
        skills: ['JavaScript', 'React', 'Node.js'],
        endorsements: [],
        openTo: ['job opportunities'],
        interests: ['technology', 'software development'],
        activityLevel: 'active',
        recommendationsReceived: 15,
        education: ['Computer Science Degree'],
        certifications: ['AWS Certified']
      },
      tikTok: {
        handle: '@sarahcodes',
        url: 'https://tiktok.com/@sarahcodes',
        bio: 'Software engineer sharing coding tips',
        followers: 1000,
        following: 200,
        totalLikes: 5000,
        videoCount: 50,
        avgViews: 1000,
        avgLikes: 100,
        avgComments: 20,
        engagementRatePct: 5.0,
        postingCadence: 'weekly',
        lastActive: '2024-01-15',
        topics: ['coding', 'tech tips'],
        contentStyle: ['educational', 'funny'],
        musicPreferences: ['upbeat', 'electronic'],
        hashtags: ['#coding', '#tech'],
        openToCollabs: true,
        linkInBio: 'https://github.com/sarahjohnson',
        region: 'US'
      },
      instagram: {
        handle: '@sarahcodes',
        url: 'https://instagram.com/sarahcodes',
        bio: 'Software engineer & tech enthusiast',
        followers: 800,
        following: 300,
        postsCount: 100,
        avgLikes: 80,
        avgComments: 15,
        engagementRatePct: 4.0,
        lastActive: '2024-01-15',
        contentThemes: ['coding', 'lifestyle'],
        storyCadence: 'daily',
        reelsSharePct: 30,
        hashtags: ['#coding', '#techlife'],
        highlights: ['coding tips', 'projects'],
        gridStyle: 'clean',
        verified: false,
        linkInBio: 'https://github.com/sarahjohnson'
      }
    },
    isOnline: true,
    lastSeen: '2024-01-15T10:30:00Z'
  },
  {
    id: '2', 
    name: 'Michael Chen',
    email: 'michael.chen@creativeagency.com',
    role: 'Marketing Manager',
    initials: 'MC',
    avatarColor: 'bg-green-500',
    monetaryValue: 65000,
    age: 32,
    company: 'Creative Agency',
    gender: 'male',
    personality: {
      traits: ['creative', 'strategic', 'analytical'],
      workStyle: 'data-driven marketing; creative campaigns',
      socialStyle: 'outgoing; enjoys networking',
      motivation: 'brand growth, creative excellence',
      stressTriggers: ['tight budgets', 'unclear objectives'],
      riskTolerance: 0.6,
      summary: 'strategic marketing manager with creative flair',
      category: 'marketing',
      ageBand: 'mid',
      interests: ['marketing', 'design', 'analytics'],
      likes: ['creative campaigns', 'data insights', 'team collaboration'],
      dislikes: ['micromanagement', 'unclear goals'],
      values: ['creativity', 'data-driven decisions', 'teamwork'],
      beliefs: ['good marketing tells a story', 'data informs creativity'],
      fears: ['campaign failure', 'budget cuts'],
      aspirations: ['marketing leadership', 'award-winning campaigns'],
      habits: ['market research', 'trend analysis'],
      goals: ['increase brand awareness', 'improve ROI'],
      challenges: ['measuring campaign success', 'budget constraints'],
      strengths: ['creativity', 'analytics', 'communication'],
      weaknesses: ['perfectionism', 'over-analysis'],
      preferences: ['collaborative environment', 'creative freedom'],
      behaviors: ['proactive', 'innovative'],
      patterns: ['research-driven', 'iterative improvement'],
      triggers: ['unclear objectives', 'budget cuts'],
      reactions: ['seeks clarification', 'proposes alternatives'],
      responses: ['creative problem-solving', 'data analysis'],
      motivations: ['creative excellence', 'business growth'],
      frustrations: ['unclear briefs', 'budget limitations']
    },
    socialMedia: {
      linkedIn: {
        url: 'https://linkedin.com/in/michaelchen',
        headline: 'Marketing Manager at Creative Agency',
        summary: 'Creative marketer passionate about brand growth',
        connections: 800,
        followers: 300,
        location: 'New York, NY',
        currentRole: { title: 'Marketing Manager', company: 'Creative Agency', startYear: 2019 },
        skills: ['Digital Marketing', 'Brand Strategy', 'Analytics'],
        endorsements: [],
        openTo: ['networking'],
        interests: ['marketing', 'branding', 'analytics'],
        activityLevel: 'very active',
        recommendationsReceived: 25,
        education: ['Marketing Degree'],
        certifications: ['Google Analytics Certified']
      },
      tikTok: {
        handle: '@mikecreates',
        url: 'https://tiktok.com/@mikecreates',
        bio: 'Marketing manager sharing creative tips',
        followers: 2000,
        following: 400,
        totalLikes: 10000,
        videoCount: 80,
        avgViews: 2000,
        avgLikes: 200,
        avgComments: 40,
        engagementRatePct: 6.0,
        postingCadence: '3x weekly',
        lastActive: '2024-01-15',
        topics: ['marketing', 'creativity'],
        contentStyle: ['educational', 'entertaining'],
        musicPreferences: ['trending', 'upbeat'],
        hashtags: ['#marketing', '#creativity'],
        openToCollabs: true,
        linkInBio: 'https://michaelchen.com',
        region: 'US'
      },
      instagram: {
        handle: '@mikecreates',
        url: 'https://instagram.com/mikecreates',
        bio: 'Marketing manager & creative strategist',
        followers: 1500,
        following: 500,
        postsCount: 200,
        avgLikes: 120,
        avgComments: 25,
        engagementRatePct: 5.0,
        lastActive: '2024-01-15',
        contentThemes: ['marketing', 'design', 'lifestyle'],
        storyCadence: 'daily',
        reelsSharePct: 40,
        hashtags: ['#marketing', '#creativity'],
        highlights: ['campaigns', 'tips'],
        gridStyle: 'aesthetic',
        verified: false,
        linkInBio: 'https://michaelchen.com'
      }
    },
    isOnline: true,
    lastSeen: '2024-01-15T09:45:00Z'
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@financesolutions.com',
    role: 'Data Analyst',
    initials: 'ER',
    avatarColor: 'bg-purple-500',
    monetaryValue: 70000,
    age: 26,
    company: 'Finance Solutions',
    gender: 'female',
    personality: {
      traits: ['analytical', 'detail-oriented', 'curious'],
      workStyle: 'data-driven analysis; systematic approach',
      socialStyle: 'thoughtful; enjoys deep conversations',
      motivation: 'insights discovery, data accuracy',
      stressTriggers: ['unclean data', 'unrealistic deadlines'],
      riskTolerance: 0.4,
      summary: 'analytical data analyst focused on insights',
      category: 'analyst',
      ageBand: 'early',
      interests: ['data science', 'statistics', 'visualization'],
      likes: ['clean data', 'meaningful insights', 'collaboration'],
      dislikes: ['messy data', 'unclear requirements'],
      values: ['accuracy', 'insights', 'collaboration'],
      beliefs: ['data tells a story', 'quality over speed'],
      fears: ['incorrect analysis', 'misleading insights'],
      aspirations: ['data science leadership', 'advanced analytics'],
      habits: ['data validation', 'continuous learning'],
      goals: ['improve data quality', 'advanced modeling'],
      challenges: ['data quality issues', 'complex requirements'],
      strengths: ['analytical thinking', 'attention to detail', 'problem-solving'],
      weaknesses: ['perfectionism', 'over-analysis'],
      preferences: ['structured environment', 'clear objectives'],
      behaviors: ['methodical', 'thorough'],
      patterns: ['data-first approach', 'validation-heavy'],
      triggers: ['unclean data', 'unclear requirements'],
      reactions: ['requests clarification', 'proposes data cleaning'],
      responses: ['systematic analysis', 'detailed documentation'],
      motivations: ['data accuracy', 'meaningful insights'],
      frustrations: ['poor data quality', 'unclear objectives']
    },
    socialMedia: {
      linkedIn: {
        url: 'https://linkedin.com/in/emilyrodriguez',
        headline: 'Data Analyst at Finance Solutions',
        summary: 'Passionate about turning data into insights',
        connections: 300,
        followers: 150,
        location: 'Chicago, IL',
        currentRole: { title: 'Data Analyst', company: 'Finance Solutions', startYear: 2021 },
        skills: ['Python', 'SQL', 'Tableau'],
        endorsements: [],
        openTo: ['job opportunities'],
        interests: ['data science', 'analytics', 'finance'],
        activityLevel: 'moderate',
        recommendationsReceived: 8,
        education: ['Statistics Degree'],
        certifications: ['Tableau Certified']
      },
      tikTok: {
        handle: '@emilydata',
        url: 'https://tiktok.com/@emilydata',
        bio: 'Data analyst sharing insights and tips',
        followers: 500,
        following: 100,
        totalLikes: 2000,
        videoCount: 30,
        avgViews: 500,
        avgLikes: 50,
        avgComments: 10,
        engagementRatePct: 4.0,
        postingCadence: 'weekly',
        lastActive: '2024-01-14',
        topics: ['data analysis', 'statistics'],
        contentStyle: ['educational', 'informative'],
        musicPreferences: ['calm', 'instrumental'],
        hashtags: ['#data', '#analytics'],
        openToCollabs: false,
        linkInBio: 'https://emilyrodriguez.com',
        region: 'US'
      },
      instagram: {
        handle: '@emilydata',
        url: 'https://instagram.com/emilydata',
        bio: 'Data analyst & visualization enthusiast',
        followers: 400,
        following: 200,
        postsCount: 50,
        avgLikes: 30,
        avgComments: 8,
        engagementRatePct: 3.0,
        lastActive: '2024-01-14',
        contentThemes: ['data viz', 'analytics', 'work'],
        storyCadence: 'weekly',
        reelsSharePct: 20,
        hashtags: ['#data', '#analytics'],
        highlights: ['visualizations', 'tips'],
        gridStyle: 'minimal',
        verified: false,
        linkInBio: 'https://emilyrodriguez.com'
      }
    },
    isOnline: true,
    lastSeen: '2024-01-15T11:15:00Z'
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.kim@designstudio.com',
    role: 'Product Designer',
    initials: 'DK',
    avatarColor: 'bg-orange-500',
    monetaryValue: 80000,
    age: 30,
    company: 'Design Studio',
    gender: 'male',
    personality: {
      traits: ['creative', 'user-focused', 'collaborative'],
      workStyle: 'user-centered design; iterative process',
      socialStyle: 'collaborative; enjoys team work',
      motivation: 'user satisfaction, design excellence',
      stressTriggers: ['unclear user needs', 'design by committee'],
      riskTolerance: 0.5,
      summary: 'user-focused product designer',
      category: 'designer',
      ageBand: 'mid',
      interests: ['design', 'user experience', 'technology'],
      likes: ['user research', 'clean design', 'collaboration'],
      dislikes: ['design by committee', 'unclear requirements'],
      values: ['user-centricity', 'design quality', 'collaboration'],
      beliefs: ['design solves problems', 'users come first'],
      fears: ['poor user experience', 'design stagnation'],
      aspirations: ['design leadership', 'award-winning products'],
      habits: ['user research', 'design iteration'],
      goals: ['improve user experience', 'design system'],
      challenges: ['balancing user needs and business goals'],
      strengths: ['creativity', 'user empathy', 'collaboration'],
      weaknesses: ['perfectionism', 'over-designing'],
      preferences: ['user research', 'iterative design'],
      behaviors: ['user-focused', 'collaborative'],
      patterns: ['research-driven', 'iterative improvement'],
      triggers: ['unclear user needs', 'design by committee'],
      reactions: ['conducts user research', 'proposes user testing'],
      responses: ['user-centered solutions', 'design iteration'],
      motivations: ['user satisfaction', 'design excellence'],
      frustrations: ['unclear user needs', 'design constraints']
    },
    socialMedia: {
      linkedIn: {
        url: 'https://linkedin.com/in/davidkim',
        headline: 'Product Designer at Design Studio',
        summary: 'Creating user-centered digital experiences',
        connections: 600,
        followers: 250,
        location: 'Seattle, WA',
        currentRole: { title: 'Product Designer', company: 'Design Studio', startYear: 2020 },
        skills: ['Figma', 'User Research', 'Prototyping'],
        endorsements: [],
        openTo: ['job opportunities'],
        interests: ['design', 'UX', 'product'],
        activityLevel: 'active',
        recommendationsReceived: 20,
        education: ['Design Degree'],
        certifications: ['Google UX Design']
      },
      tikTok: {
        handle: '@davidcreates',
        url: 'https://tiktok.com/@davidcreates',
        bio: 'Product designer sharing UX tips',
        followers: 1500,
        following: 300,
        totalLikes: 8000,
        videoCount: 60,
        avgViews: 1500,
        avgLikes: 150,
        avgComments: 30,
        engagementRatePct: 5.5,
        postingCadence: '2x weekly',
        lastActive: '2024-01-15',
        topics: ['UX design', 'product design'],
        contentStyle: ['educational', 'visual'],
        musicPreferences: ['chill', 'electronic'],
        hashtags: ['#UX', '#design'],
        openToCollabs: true,
        linkInBio: 'https://davidkim.design',
        region: 'US'
      },
      instagram: {
        handle: '@davidcreates',
        url: 'https://instagram.com/davidcreates',
        bio: 'Product designer & UX enthusiast',
        followers: 1200,
        following: 400,
        postsCount: 150,
        avgLikes: 90,
        avgComments: 20,
        engagementRatePct: 4.5,
        lastActive: '2024-01-15',
        contentThemes: ['design', 'UX', 'lifestyle'],
        storyCadence: 'daily',
        reelsSharePct: 35,
        hashtags: ['#UX', '#design'],
        highlights: ['designs', 'process'],
        gridStyle: 'clean',
        verified: false,
        linkInBio: 'https://davidkim.design'
      }
    },
    isOnline: true,
    lastSeen: '2024-01-15T08:20:00Z'
  },
  {
    id: '5',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@enterprisesolutions.com',
    role: 'Sales Director',
    initials: 'LT',
    avatarColor: 'bg-red-500',
    monetaryValue: 95000,
    age: 35,
    company: 'Enterprise Solutions',
    gender: 'female',
    personality: {
      traits: ['driven', 'strategic', 'relationship-focused'],
      workStyle: 'results-driven; relationship building',
      socialStyle: 'outgoing; enjoys networking',
      motivation: 'revenue growth, team success',
      stressTriggers: ['missed targets', 'difficult clients'],
      riskTolerance: 0.8,
      summary: 'results-driven sales director',
      category: 'sales',
      ageBand: 'senior',
      interests: ['sales', 'leadership', 'strategy'],
      likes: ['team success', 'client relationships', 'growth'],
      dislikes: ['micromanagement', 'unclear goals'],
      values: ['results', 'relationships', 'integrity'],
      beliefs: ['relationships drive sales', 'team success is key'],
      fears: ['missing targets', 'team failure'],
      aspirations: ['VP of Sales', 'company growth'],
      habits: ['team coaching', 'client meetings'],
      goals: ['exceed targets', 'develop team'],
      challenges: ['market competition', 'team motivation'],
      strengths: ['leadership', 'relationship building', 'strategy'],
      weaknesses: ['impatience', 'over-commitment'],
      preferences: ['autonomous environment', 'clear targets'],
      behaviors: ['results-focused', 'collaborative'],
      patterns: ['goal-oriented', 'team development'],
      triggers: ['missed targets', 'team issues'],
      reactions: ['analyzes performance', 'coaches team'],
      responses: ['strategic planning', 'team motivation'],
      motivations: ['revenue growth', 'team success'],
      frustrations: ['unclear targets', 'team underperformance']
    },
    socialMedia: {
      linkedIn: {
        url: 'https://linkedin.com/in/lisathompson',
        headline: 'Sales Director at Enterprise Solutions',
        summary: 'Driving revenue growth through strategic sales leadership',
        connections: 1000,
        followers: 400,
        location: 'Austin, TX',
        currentRole: { title: 'Sales Director', company: 'Enterprise Solutions', startYear: 2018 },
        skills: ['Sales Leadership', 'Strategy', 'CRM'],
        endorsements: [],
        openTo: ['networking'],
        interests: ['sales', 'leadership', 'strategy'],
        activityLevel: 'very active',
        recommendationsReceived: 35,
        education: ['Business Degree'],
        certifications: ['Sales Management Certified']
      },
      tikTok: {
        handle: '@lisasells',
        url: 'https://tiktok.com/@lisasells',
        bio: 'Sales director sharing leadership tips',
        followers: 3000,
        following: 500,
        totalLikes: 15000,
        videoCount: 100,
        avgViews: 3000,
        avgLikes: 300,
        avgComments: 60,
        engagementRatePct: 7.0,
        postingCadence: 'daily',
        lastActive: '2024-01-15',
        topics: ['sales', 'leadership'],
        contentStyle: ['motivational', 'educational'],
        musicPreferences: ['upbeat', 'motivational'],
        hashtags: ['#sales', '#leadership'],
        openToCollabs: true,
        linkInBio: 'https://lisathompson.com',
        region: 'US'
      },
      instagram: {
        handle: '@lisasells',
        url: 'https://instagram.com/lisasells',
        bio: 'Sales director & leadership coach',
        followers: 2000,
        following: 600,
        postsCount: 300,
        avgLikes: 150,
        avgComments: 35,
        engagementRatePct: 6.0,
        lastActive: '2024-01-15',
        contentThemes: ['sales', 'leadership', 'lifestyle'],
        storyCadence: 'daily',
        reelsSharePct: 50,
        hashtags: ['#sales', '#leadership'],
        highlights: ['tips', 'success stories'],
        gridStyle: 'professional',
        verified: false,
        linkInBio: 'https://lisathompson.com'
      }
    },
    isOnline: true,
    lastSeen: '2024-01-15T07:30:00Z'
  }
]

async function testPostGeneration() {
  console.log('🧪 Testing OpenAI-powered social media post generation...\n')
  
  for (const citizen of sampleCitizens) {
    try {
      console.log(`👤 Testing with ${citizen.name} (${citizen.role} at ${citizen.company})`)
      console.log('='.repeat(60))
      
      const post = await SocialMediaPostGenerator.generatePost(citizen)
      
      console.log(`📱 Platform: ${post.platform.toUpperCase()}`)
      console.log(`📝 Content:`)
      console.log(post.content)
      console.log(`\n🏷️  Hashtags: ${post.hashtags.join(' ')}`)
      console.log(`⏰ Generated: ${post.timestamp.toLocaleString()}`)
      console.log('='.repeat(60))
      console.log('')
      
    } catch (error) {
      console.error(`❌ Error generating post for ${citizen.name}:`, error instanceof Error ? error.message : 'Unknown error')
      console.log('')
    }
  }
  
  console.log('✅ Test completed!')
}

// Run the test
testPostGeneration().catch(console.error)
